# Generated by Django 4.2.7 on 2023-11-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
